// src/app/presentation/components/shared/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {
  year = new Date().getFullYear();
  nickname = 'lunaticfriki';
  githubUrl = 'http://www.github.com/lunaticfriki';
}

<footer>
  <a href="{{ githubUrl }}" target="_blank">
    &#64;{{ nickname }}, <span>{{ year }}</span>
  </a>
</footer>

// src/presentation/components/footer.component.tsx
export const FooterComponent = () => {
  return (
    <footer className="p-4">
      <a
        href="https://github.com/lunaticfriki"
        target="_blank"
        rel="noopener noreferrer"
        className="text-white"
      >
        @lunaticfriki,
        <span className="text-pink-500">{new Date().getFullYear()}</span>
      </a>
    </footer>
  );
};
